workflows:
    migration_tool:
        type: 'state_machine'
        audit_trail:
            enabled: false
        marking_store:
            type: 'single_state'
            arguments:
                - 'currentState'
        supports:
            - 'Akeneo\PimMigration\Domain\MigrationToolStateMachine'
        places:
            - 'ready'
            - 'source_pim_location_guessed'
            - 'source_pim_configured'
            - 'source_pim_detected'
            - 'ee_access_pending'
            - 'all_accesses_granted'
            - 'destination_pim_location_guessed'
            - 'destination_pim_downloaded'
            - 'destination_pim_pre_configured'
            - 'destination_pim_configured'
            - 'destination_pim_detected'
            - 'destination_pim_system_requirements_installed'
            - 'destination_pim_requirements_checked'
            - 'destination_pim_file_database_migrated'
            - 'destination_pim_structure_migrated'
            - 'destination_pim_family_migrated'
            - 'destination_pim_system_migrated'
            - 'destination_pim_job_migrated'
            - 'destination_pim_extra_data_migrated'
            - 'destination_pim_reference_data_migrated'
        transitions:
            ask_source_pim_location:
                from: 'ready'
                to: 'source_pim_location_guessed'
            local_source_pim_configuration:
                from: 'source_pim_location_guessed'
                to: 'source_pim_configured'
            distant_source_pim_configuration:
                from: 'source_pim_location_guessed'
                to: 'source_pim_configured'
            source_pim_detection:
                from: 'source_pim_configured'
                to: 'source_pim_detected'
            grant_all_accesses:
                from: 'source_pim_detected'
                to: 'all_accesses_granted'
            ee_ask_an_ssh_key:
                from: 'source_pim_detected'
                to: 'ee_access_pending'
            grant_ee_accesses:
                from: 'ee_access_pending'
                to: 'all_accesses_granted'
            ask_destination_pim_location:
                from: 'all_accesses_granted'
                to: 'destination_pim_location_guessed'
            download_destination_pim:
                from: 'destination_pim_location_guessed'
                to: 'destination_pim_downloaded'
            destination_pim_pre_configuration:
                from: 'destination_pim_downloaded'
                to: 'destination_pim_pre_configured'
            destination_pim_configuration:
                from: ['destination_pim_downloaded', 'destination_pim_pre_configured']
                to: 'destination_pim_configured'
            destination_pim_detection:
                from: 'destination_pim_configured'
                to: 'destination_pim_detected'
            docker_destination_pim_system_requirements_installation:
                from: 'destination_pim_detected'
                to: 'destination_pim_system_requirements_installed'
            local_destination_pim_system_requirements_installation:
                from: 'destination_pim_detected'
                to: 'destination_pim_system_requirements_installed'
            destination_pim_check_requirements:
                from: 'destination_pim_system_requirements_installed'
                to: 'destination_pim_requirements_checked'
            destination_pim_file_database_migration:
                from: 'destination_pim_requirements_checked'
                to: 'destination_pim_file_database_migrated'
            destination_pim_structure_migration:
                from: 'destination_pim_file_database_migrated'
                to: 'destination_pim_structure_migrated'
            destination_pim_family_migration:
                from: 'destination_pim_structure_migrated'
                to: 'destination_pim_family_migrated'
            destination_pim_system_migration:
                from: 'destination_pim_family_migrated'
                to: 'destination_pim_system_migrated'
            destination_pim_job_migration:
                from: 'destination_pim_system_migrated'
                to: 'destination_pim_job_migrated'
            destination_pim_extra_data_migration:
                from: 'destination_pim_job_migrated'
                to: 'destination_pim_extra_data_migrated'
            destination_pim_reference_data_migration:
                from: 'destination_pim_extra_data_migrated'
                to: 'destination_pim_reference_data_migrated'
