services:
  _defaults:
    autoconfigure: true
    autowire: true

  _instanceof:
    Akeneo\PimMigration\Infrastructure\StateMachineTransition\StateMachineSubscriber:
      tags: ['migration_tool.subscriber']

  Akeneo\PimMigration\Infrastructure\StateMachineTransition\:
    resource: './../../StateMachineTransition/*'

  Akeneo\PimMigration\Infrastructure\DatabaseServices\DumpTableMigrator: ~
  Akeneo\PimMigration\Domain\DataMigration\TableMigrator: '@Akeneo\PimMigration\Infrastructure\DatabaseServices\DumpTableMigrator'

  Akeneo\PimMigration\Infrastructure\DatabaseServices\MySqlQueryExecutor: ~
  Akeneo\PimMigration\Domain\DataMigration\DatabaseQueryExecutor: '@Akeneo\PimMigration\Infrastructure\DatabaseServices\MySqlQueryExecutor'

### COMMAND
  Akeneo\PimMigration\Infrastructure\Command\LocalCommandExecutor: ~

  Akeneo\PimMigration\Infrastructure\Command\LocalCommandLauncher:
    class: 'Akeneo\PimMigration\Infrastructure\Command\BasicCommandLauncher'
    arguments:
      $commandExecutor: '@Akeneo\PimMigration\Infrastructure\Command\LocalCommandExecutor'

### DATA MIGRATION HELPERS

  Akeneo\PimMigration\Infrastructure\DatabaseServices\LocalCommandTableNamesFetcher:
    class: 'Akeneo\PimMigration\Infrastructure\DatabaseServices\CommandTableNamesFetcher'
    arguments:
      $commandLauncher: '@Akeneo\PimMigration\Infrastructure\Command\LocalCommandLauncher'


### STRUCTURE MIGRATORS

  Akeneo\PimMigration\Domain\StructureMigration\StructureMigrator: ~

  Akeneo\PimMigration\Domain\StructureMigration\LocaleStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_locale'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\CurrencyStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_currency'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\CategoryStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_category'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\CategoryTranslationStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_category_translation'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\AttributeGroupStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_attribute_group'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\AttributeGroupTranslationStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_attribute_group_translation'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\GroupTypeStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_group_type'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\GroupTypeStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_group_type_translation'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\ChannelStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_channel'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\ChannelCurrencyStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_channel_currency'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\ChannelLocaleStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_channel_locale'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\ChannelTranslationStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_channel_translation'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\AssociationTypeStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_association_type'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\AssociationTypeTranslationStructureMigrator:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_association_type_translation'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\AttributeDataMigrator:
    class: 'Akeneo\PimMigration\Domain\StructureMigration\AttributeDataMigrator'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\AttributeLocal:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_attribute_locale'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\AttributeTranslation:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_attribute_translation'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\AttributeOption:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_attribute_option'
    tags: ['migration_tool.structure_migrator']

  Akeneo\PimMigration\Domain\StructureMigration\AttributeOptionValue:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_catalog_attribute_option_value'
    tags: ['migration_tool.structure_migrator']

## SYSTEM MIGRATORS

  Akeneo\PimMigration\Domain\SystemMigration\SystemMigrator: ~

  Akeneo\PimMigration\SystemMigration\AclClasses:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'acl_classes'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\AclSecurityIdentities:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'acl_security_identities'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\AclObjectIdentities:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'acl_object_identities'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\AclEntries:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'acl_entries'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\AclObjectIdentityAncestors:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'acl_object_identity_ancestors'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\OroAccessGroup:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'oro_access_group'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\OroAccessRole:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'oro_access_role'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\OroUserAccessGrouprole:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'oro_user_access_group_role'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\OroUser:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'oro_user'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\OroUserAccessGroup:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'oro_user_access_group'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\OroUserAccessRole:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'oro_user_access_role'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\OroConfig:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'oro_config'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\OroConfigValue:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'oro_config_value'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\PimApiAccessToken:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_api_access_token'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\PimApiAuthCode:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_api_auth_code'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\PimApiClient:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_api_client'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\PimApiRefreshToken:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_api_refresh_token'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\PimSession:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_session'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\PimDatagridView:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_datagrid_view'
    tags: ['migration_tool.system_migrator']

  Akeneo\PimMigration\SystemMigration\PimUserDefaultDatagridView:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'pim_user_default_datagrid_view'
    tags: ['migration_tool.system_migrator']

### JOB MIGRATOR

  Akeneo\PimMigration\Domain\JobMigration\JobMigrator: ~

  Akeneo\PimMigration\JobMigration\AkeneoBatchJobInstance:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'akeneo_batch_job_instance'
    tags: ['migration_tool.job_migrator']

  Akeneo\PimMigration\JobMigration\AkeneoBatchJobExecution:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'akeneo_batch_job_execution'
    tags: ['migration_tool.job_migrator']

  Akeneo\PimMigration\JobMigration\AkeneoBatchStepExecution:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'akeneo_batch_step_execution'
    tags: ['migration_tool.job_migrator']

  Akeneo\PimMigration\JobMigration\AkeneoBatchWarning:
    class: 'Akeneo\PimMigration\Domain\DataMigration\SimpleDataMigrator'
    arguments:
      $supportedTableName: 'akeneo_batch_warning'
    tags: ['migration_tool.job_migrator']
